version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    volumes:
      - data:/var/lib/postgresql/data
  server:
    image: cosmtrek/air
    working_dir: /project-package
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
    volumes:
      - ./:/project-package/
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  data:
