// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/order/repository_order/irepository_order.go

// Package mocks is a generated GoMock package.
package mocks

import (
	order "property-finder-go-bootcamp-homework/internal/domain/order"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepositoryOrder is a mock of IRepositoryOrder interface.
type MockIRepositoryOrder struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryOrderMockRecorder
}

// MockIRepositoryOrderMockRecorder is the mock recorder for MockIRepositoryOrder.
type MockIRepositoryOrderMockRecorder struct {
	mock *MockIRepositoryOrder
}

// NewMockIRepositoryOrder creates a new mock instance.
func NewMockIRepositoryOrder(ctrl *gomock.Controller) *MockIRepositoryOrder {
	mock := &MockIRepositoryOrder{ctrl: ctrl}
	mock.recorder = &MockIRepositoryOrderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryOrder) EXPECT() *MockIRepositoryOrderMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockIRepositoryOrder) CreateOrder(newOrder order.Order) (order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", newOrder)
	ret0, _ := ret[0].(order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockIRepositoryOrderMockRecorder) CreateOrder(newOrder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockIRepositoryOrder)(nil).CreateOrder), newOrder)
}

// GetOrderByUserID mocks base method.
func (m *MockIRepositoryOrder) GetOrderByUserID(userID uint) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByUserID", userID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByUserID indicates an expected call of GetOrderByUserID.
func (mr *MockIRepositoryOrderMockRecorder) GetOrderByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByUserID", reflect.TypeOf((*MockIRepositoryOrder)(nil).GetOrderByUserID), userID)
}

// GetOrderFromLastMonth mocks base method.
func (m *MockIRepositoryOrder) GetOrderFromLastMonth(userID uint) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderFromLastMonth", userID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderFromLastMonth indicates an expected call of GetOrderFromLastMonth.
func (mr *MockIRepositoryOrderMockRecorder) GetOrderFromLastMonth(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderFromLastMonth", reflect.TypeOf((*MockIRepositoryOrder)(nil).GetOrderFromLastMonth), userID)
}
