name: github-pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go get -v -d ./...
          go install gotest.tools/gotestsum@latest    
          go install github.com/golang/mock/mockgen@v1.6.0


      - name: Create env file
        run:
          touch .env

      - name: Write to env
        run:
          echo "POSTGRES_HOST=database
          POSTGRES_PORT=5432
          POSTGRES_USER=postgres
          POSTGRES_PASS=mysecretpassword
          POSTGRES_DB=mydb
          POSTGRES_SSL=disable
          POSTGRES_HOST_AUTH_METHOD=trust
          JWT_SECRET_KEY=47odVACvzCPLwObhhTybose4m2E2uq783v8hvuMYKKQCK0oGAy
          PORT=8080
          GIVEN_AMOUNT=500" > .env

      - name: Build
        run: make run

      - name: Create Mocks
        run:
          make make-mocks
      - name: Test
        run:  make run-test  # run-test is a custom command in Makefile